### ISSUE TITLE
write_str_fixed with cp932

### ISSUE THREAD

**Issue by SamuraiOndo** [SutandoTsukai181/PyBinaryReader#2]
The current way write_str_fixed is implemented does not work with cp932, as each character is two bytes.  Because it reads the string length and not how many bytes there are, it doesn't write the correct buffer length. 

Multiplying the string length by two solves this in SOME cases, but it does not account for the spaces which are just one byte.  This is surely an issue for other multiple byte encodings, although I only know it is a problem for cp932.

**Comment by mosamadeeb** [comment]
Just to make sure, you're expecting the number of bytes to be written to be equal to the size argument, right?
